import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { Activity, Brain, LogOut, Maximize2, Network, ScanLine, Upload, Waves, X } from "lucide-react";
import { VolumeBrain, type VolumeData } from "./VolumeBrain";

type Mode = "VOLUME" | "HEATMAP" | "TRACTS" | "EEG" | "CONNECTOME";
type Track = number[][];
type Stats = { voxels:number; min:number; max:number; mean:number; std:number; dims:[number,number,number]; datatype:string; bitpix:number };

type Dataset = { volume: VolumeData; stats: Stats };

const demoDataset = (): Dataset => {
  const n=112, data=new Uint8Array(n*n*n), c=(n-1)/2;
  let sum=0, sum2=0, count=0, min=255, max=0;
  for(let z=0;z<n;z++) for(let y=0;y<n;y++) for(let x=0;x<n;x++) {
    const X=(x-c)/c,Y=(y-c)/c,Z=(z-c)/c;
    const r=X*X/.9+Y*Y/.78+Z*Z/.84;
    const cortex=0.06*Math.sin(Y*42+Z*9)+0.025*Math.sin(Y*81-Z*11)+0.018*Math.sin((Y+Z)*110);
    let v=r<1+cortex ? 38+180*Math.pow(Math.max(0,1-r),.58) : 0;
    const deep=32*Math.exp(-(X*X/.22+Y*Y/.28+Z*Z/.31));
    const vent=((X/.19)**2+((Y+.02)/.30)**2+((Z+.02)/.25)**2)<1;
    if(vent)v*=.25;
    v=Math.max(0,Math.min(255,v+deep));
    const i=x+n*(y+n*z); data[i]=v; sum+=v; sum2+=v*v; count++; min=Math.min(min,v); max=Math.max(max,v);
  }
  return {volume:{data,size:[n,n,n]},stats:{voxels:count,min,max,mean:sum/count,std:Math.sqrt(Math.max(0,sum2/count-(sum/count)**2)),dims:[n,n,n],datatype:"demo T1",bitpix:8}};
};

function parseNifti(buffer:ArrayBuffer): Dataset | null {
  const v=new DataView(buffer); if(v.byteLength<352)return null;
  const le=v.getInt32(0,true)===348; if(!le && v.getInt32(0,false)!==348)return null;
  const i16=(o:number)=>v.getInt16(o,le), i32=(o:number)=>v.getInt32(o,le), f32=(o:number)=>v.getFloat32(o,le);
  const nx=i16(42),ny=i16(44),nz=i16(46),dt=i16(70),bp=i16(72); if(nx<2||ny<2||nz<2)return null;
  const slope=f32(112)||1, intercept=f32(116)||0, off=Math.max(352, f32(108)||352), bytes=bp/8, total=nx*ny*nz;
  if(!Number.isFinite(off)||bp%8||off+total*bytes>v.byteLength)return null;
  const raw=(i:number)=>{const o=off+i*bytes;switch(dt){case 2:return v.getUint8(o);case 4:return v.getInt16(o,le);case 8:return v.getInt32(o,le);case 16:return v.getFloat32(o,le);case 64:return v.getFloat64(o,le);case 256:return v.getInt8(o);case 512:return v.getUint16(o,le);case 768:return v.getUint32(o,le);default:return 0;}};
  const read=(i:number)=>raw(i)*slope+intercept;
  let min=Infinity,max=-Infinity,sum=0,sum2=0,samp=0; const step=Math.max(1,Math.ceil(Math.cbrt(total/250000)));
  for(let z=0;z<nz;z+=step)for(let y=0;y<ny;y+=step)for(let x=0;x<nx;x+=step){const q=read(x+nx*(y+ny*z));if(Number.isFinite(q)){min=Math.min(min,q);max=Math.max(max,q);sum+=q;sum2+=q*q;samp++;}}
  if(!Number.isFinite(min)||!Number.isFinite(max))return null;
  const n=128,out=new Uint8Array(n*n*n),range=max-min||1;
  const clamp=(a:number,b:number)=>Math.max(0,Math.min(a,b));
  for(let z=0;z<n;z++)for(let y=0;y<n;y++)for(let x=0;x<n;x++){
    const fx=x*(nx-1)/(n-1),fy=y*(ny-1)/(n-1),fz=z*(nz-1)/(n-1),x0=Math.floor(fx),y0=Math.floor(fy),z0=Math.floor(fz),x1=Math.min(nx-1,x0+1),y1=Math.min(ny-1,y0+1),z1=Math.min(nz-1,z0+1),xd=fx-x0,yd=fy-y0,zd=fz-z0;
    const g=(xx:number,yy:number,zz:number)=>read(xx+nx*(yy+ny*zz));
    const c000=g(x0,y0,z0),c100=g(x1,y0,z0),c010=g(x0,y1,z0),c110=g(x1,y1,z0),c001=g(x0,y0,z1),c101=g(x1,y0,z1),c011=g(x0,y1,z1),c111=g(x1,y1,z1);
    const c00=c000+(c100-c000)*xd,c10=c010+(c110-c010)*xd,c01=c001+(c101-c001)*xd,c11=c011+(c111-c011)*xd,c0=c00+(c10-c00)*yd,c1=c01+(c11-c01)*yd,q=clamp((c0+(c1-c0)*zd-min)/range,0,1);
    out[x+n*(y+n*z)]=Math.round(q*255);
  }
  return {volume:{data:out,size:[n,n,n]},stats:{voxels:total,min,max,mean:sum/samp,std:Math.sqrt(Math.max(0,sum2/samp-(sum/samp)**2)),dims:[nx,ny,nz],datatype:`NIfTI ${dt}`,bitpix:bp}};
}

function SliceMap({volume,axis,heat=false}:{volume:VolumeData;axis:0|1|2;heat?:boolean}){
  const ref=useRef<HTMLCanvasElement>(null); useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const [nx,ny,nz]=volume.size;const W=300,H=300;c.width=W;c.height=H;const img=ctx.createImageData(W,H);const d=volume.data;
    const idx=(x:number,y:number,z:number)=>d[x+nx*(y+ny*z)]||0;
    for(let j=0;j<H;j++)for(let i=0;i<W;i++){let x=Math.floor(i*(nx-1)/(W-1)),y=Math.floor(j*(ny-1)/(H-1)),z=Math.floor((W-1-i)*(nz-1)/(W-1));if(axis===1)y=Math.floor(i*(ny-1)/(W-1)),x=Math.floor(j*(nx-1)/(H-1));if(axis===2)z=Math.floor(i*(nz-1)/(W-1)),x=Math.floor(j*(nx-1)/(H-1));const q=idx(x,y,z)/255,p=(j*W+i)*4;if(heat){const h=(1-q)*240;const c1=Math.max(0,Math.min(255,255*Math.abs(((h/60)%2)-1)));const c2=Math.max(0,Math.min(255,255*(1-Math.abs((h/60)%2-1))));img.data[p]=q*255;img.data[p+1]=c2;img.data[p+2]=c1;img.data[p+3]=q>0.025?210:0;}else{const g=Math.pow(q,.55)*255;img.data[p]=g;img.data[p+1]=g;img.data[p+2]=g;img.data[p+3]=q>0.025?235:0;}}ctx.putImageData(img,0,0)},[volume,axis,heat]);return <canvas ref={ref} className="h-full w-full"/>;
}

function Tractography({activeROI}:{activeROI:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d")!;let raf=0,t=0;const bundles=480;const draw=()=>{t+=.004;const w=c.clientWidth,h=c.clientHeight,d=Math.min(devicePixelRatio||1,2);if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0)}ctx.clearRect(0,0,w,h);for(let k=0;k<bundles;k++){const b=k%8,phase=k*.173,pts=72;ctx.beginPath();for(let i=0;i<pts;i++){const u=i/(pts-1),x=(u-.5)*2.2,y0=((k%48)-24)/34,z0=Math.sin(k*.71)*.35;let y=y0,z=z0;if(b===0){y*=.35;z+=Math.sin(u*Math.PI)*.4}else if(b===1){y+=Math.sin(u*Math.PI)*.55;z+=Math.cos(u*Math.PI)*.15}else if(b===2){z+=Math.sin(u*Math.PI)*.7;y+=Math.sin(u*2*Math.PI)*.18}else if(b===3){y-=Math.sin(u*Math.PI)*.65;z+=Math.sin(u*Math.PI)*.28}else if(b===4){y+=Math.sin(u*2*Math.PI)*.3;z-=Math.sin(u*Math.PI)*.45}else if(b===5){x+=Math.sin(u*Math.PI)*.22;y+=Math.sin(u*3*Math.PI)*.2}else if(b===6){y+=Math.cos(u*Math.PI)*.32;z+=Math.sin(u*Math.PI*2)*.28}else{y+=Math.sin(u*Math.PI)*.7* (k%2?-1:1);z+=Math.sin(u*Math.PI)*.15}const X=x*Math.cos(t)-z*Math.sin(t),Z=x*Math.sin(t)+z*Math.cos(t),pers=3.2/(3.6-Z),sx=w/2+X*w*.3*pers,sy=h/2+y*h*.28*pers;i?ctx.lineTo(sx,sy):ctx.moveTo(sx,sy)}const hue=b%3===0?190:b%3===1?220:285;ctx.strokeStyle=`hsla(${hue},100%,${b===0?78:68}%,${b===0?.8:.38})`;ctx.lineWidth=b===0?1.8:.8;ctx.shadowBlur=b===0?8:2;ctx.shadowColor=`hsla(${hue},100%,70%,.8)`;ctx.stroke()}ctx.shadowBlur=0;ctx.fillStyle="#9dfcff";ctx.font="10px monospace";ctx.fillText(`ROI FOCUS / ${activeROI.toUpperCase()}`,18,28);raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[activeROI]);return <canvas ref={ref} className="h-full w-full"/>}

function EEGPanel(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d")!;let raf=0,t=0;const draw=()=>{t+=.02;const w=c.clientWidth,h=c.clientHeight,d=Math.min(devicePixelRatio||1,2);if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0)}ctx.clearRect(0,0,w,h);for(let ch=0;ch<8;ch++){ctx.beginPath();for(let i=0;i<w;i+=2){const y=18+ch*(h-36)/8+Math.sin(i*.025+t*(1+ch*.03))*8+Math.sin(i*.13+t*1.7)*2.5+Math.sin(i*.004+t*.35)*7;i?ctx.lineTo(i,y):ctx.moveTo(i,y)}ctx.strokeStyle=`rgba(70,255,188,${.72-ch*.04})`;ctx.lineWidth=1.2;ctx.stroke()}raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[]);return <canvas ref={ref} className="h-full w-full"/>}

function Stat({label,value,unit}:{label:string;value:string;unit?:string}){return <div className="rounded-xl border border-white/10 bg-white/[.018] p-4"><div className="font-mono text-[7px] tracking-[.22em] text-white/30">{label}</div><div className="mt-2 text-xl font-light text-white/85">{value}<span className="ml-1 text-[9px] text-cyan-200/40">{unit}</span></div></div>}

export function NimbleRealTimeAnalysis(){
  const navigate=useNavigate();
  const [dataset,setDataset]=useState<Dataset>(()=>demoDataset()); const [mode,setMode]=useState<Mode>("VOLUME"); const [axis,setAxis]=useState<0|1|2>(2); const [heat,setHeat]=useState(true); const [roi,setRoi]=useState("Whole brain"); const [analysis,setAnalysis]=useState("READY"); const [fileName,setFileName]=useState("NIMBLE_REFERENCE_T1"); const [eeg,setEeg]=useState(false); const [tracts,setTracts]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  const quality=useMemo(()=>Math.min(99,82+(dataset.stats.std/dataset.stats.max)*12),[dataset]);
  const uploadNifti=(f:File)=>{setAnalysis("PARSING VOXELS…");f.arrayBuffer().then(b=>{const parsed=parseNifti(b);if(parsed){setDataset(parsed);setFileName(f.name);setAnalysis("VOLUME READY")}else setAnalysis("NIfTI PARSE ERROR")}).catch(()=>setAnalysis("READ ERROR"))};
  const logout=()=>{localStorage.removeItem("cognivance_session");navigate({to:"/auth"})};
  return <div className="min-h-[calc(100vh-57px)] bg-[#020405] text-white">
    <input ref={fileRef} type="file" accept=".nii,.nii.gz" className="hidden" onChange={e=>e.target.files?.[0]&&uploadNifti(e.target.files[0])}/>
    <div className="border-b border-white/10 bg-[#030608]/95 px-4 py-3"><div className="mx-auto flex max-w-[1900px] items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg border border-cyan-200/20 bg-cyan-200/[.04]"><Brain size={16} className="text-cyan-100"/></div><div><div className="font-mono text-[8px] tracking-[.35em] text-cyan-100/70">NIMBLE / RESEARCH OS</div><div className="font-mono text-[6px] tracking-[.18em] text-white/25">MULTIMODAL NEUROIMAGING • LIVE</div></div></div><div className="flex items-center gap-2"><span className="hidden font-mono text-[7px] text-emerald-300/60 sm:inline">● {analysis}</span><button onClick={()=>navigate({to:"/"})} className="rounded-full border border-white/10 px-3 py-2 font-mono text-[7px] tracking-[.18em] text-white/45 hover:border-cyan-200/30 hover:text-white">← HOME</button><button onClick={logout} className="flex items-center gap-1.5 rounded-full border border-red-200/10 px-3 py-2 font-mono text-[7px] tracking-[.18em] text-red-200/60 hover:border-red-200/30 hover:text-red-100"><LogOut size={11}/> LOGOUT</button></div></div></div>
    <main className="mx-auto grid max-w-[1900px] gap-3 p-3 lg:grid-cols-[260px_minmax(0,1fr)_300px]">
      <aside className="space-y-3"><section className="rounded-xl border border-white/10 bg-white/[.015] p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/25">DATA INGEST</div><button onClick={()=>fileRef.current?.click()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg border border-cyan-200/20 bg-cyan-200/[.05] py-3 font-mono text-[7px] tracking-[.18em] text-cyan-100 hover:bg-cyan-200/10"><Upload size={12}/> UPLOAD NIFTI</button><div className="mt-3 truncate font-mono text-[7px] text-white/40">{fileName}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setEeg(v=>!v)} className={`rounded-lg border px-2 py-3 font-mono text-[7px] ${eeg?"border-emerald-300/30 bg-emerald-300/10 text-emerald-100":"border-white/10 text-white/35"}`}><Waves size={12} className="mx-auto mb-1"/>EEG</button><button onClick={()=>setTracts(v=>!v)} className={`rounded-lg border px-2 py-3 font-mono text-[7px] ${tracts?"border-violet-300/30 bg-violet-300/10 text-violet-100":"border-white/10 text-white/35"}`}><Network size={12} className="mx-auto mb-1"/>TRACTS</button></div></section><section className="rounded-xl border border-white/10 p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/25">VISUAL LAYERS</div>{([["VOLUME","3D volume",Brain],["HEATMAP","metabolic heatmap",Activity],["TRACTS","fiber architecture",Network],["EEG","temporal signal",Waves],["CONNECTOME","network topology",ScanLine]] as const).map(([m,label,I])=><button key={m} onClick={()=>setMode(m)} className={`mt-2 flex w-full items-center gap-3 rounded-lg border px-3 py-3 text-left ${mode===m?"border-cyan-200/25 bg-cyan-200/[.06] text-cyan-100":"border-white/5 text-white/35 hover:bg-white/[.03]"}`}><I size={13}/><span className="font-mono text-[7px] tracking-[.12em]">{label}</span></button>)}</section></aside>
      <section className="min-h-[700px] overflow-hidden rounded-2xl border border-white/10 bg-[#030608] relative"><div className="absolute inset-x-0 top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#030608]/80 px-4 py-3 backdrop-blur"><div><div className="font-mono text-[7px] tracking-[.25em] text-cyan-100/60">{mode} / REAL-TIME VIEW</div><div className="font-mono text-[6px] text-white/25">ROI: {roi} • RESOLUTION: {dataset.volume.size.join("×")}</div></div><div className="flex gap-1">{[0,1,2].map(a=><button key={a} onClick={()=>setAxis(a as 0|1|2)} className={`rounded border px-2 py-1 font-mono text-[6px] ${axis===a?"border-cyan-200/30 text-cyan-100":"border-white/10 text-white/25"}`}>{["AX","COR","SAG"][a]}</button>)}</div></div>{mode==="VOLUME"&&<div className="absolute inset-0 pt-14"><VolumeBrain volume={dataset.volume} mode="ANATOMY"/></div>}{mode==="HEATMAP"&&<div className="absolute inset-0 pt-14"><SliceMap volume={dataset.volume} axis={axis} heat/><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_20%,#030608_88%)] pointer-events-none"/></div>}{mode==="TRACTS"&&<div className="absolute inset-0 pt-14"><Tractography activeROI={roi}/></div>}{mode==="EEG"&&<div className="absolute inset-0 pt-14 p-5"><EEGPanel/></div>}{mode==="CONNECTOME"&&<div className="absolute inset-0 pt-14 flex items-center justify-center"><div className="relative h-[70%] aspect-square">{Array.from({length:34}).map((_,i)=>{const a=i/34*Math.PI*2,r=.32+.1*Math.sin(i*1.7),x=50+Math.cos(a)*r*100,y=50+Math.sin(a)*r*100;return <span key={i} className="absolute h-2 w-2 rounded-full bg-cyan-200 shadow-[0_0_14px_rgba(120,240,255,.8)]" style={{left:`${x}%`,top:`${y}%`}}/>})}<div className="absolute inset-[30%] rounded-full border border-violet-200/20 bg-violet-300/5 shadow-[0_0_80px_rgba(120,80,255,.12)]"/></div></div>}<div className="absolute bottom-4 left-4 right-4 z-10 grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="VOXELS" value={(dataset.stats.voxels/1e6).toFixed(2)} unit="M"/><Stat label="MEAN" value={dataset.stats.mean.toFixed(2)}/><Stat label="STD" value={dataset.stats.std.toFixed(2)}/><Stat label="QC SCORE" value={quality.toFixed(1)} unit="%"/></div></section>
      <aside className="space-y-3"><section className="rounded-xl border border-cyan-200/10 bg-cyan-200/[.02] p-4"><div className="flex items-center justify-between"><div className="font-mono text-[7px] tracking-[.25em] text-cyan-100/50">REAL-TIME ANALYSIS</div><Activity size={13} className="text-cyan-200/50"/></div><div className="mt-4 space-y-3"><div><div className="flex justify-between font-mono text-[7px] text-white/30"><span>VOLUME QUALITY</span><span>{quality.toFixed(1)}%</span></div><div className="mt-1 h-1 rounded bg-white/10"><div className="h-full rounded bg-cyan-300" style={{width:`${quality}%`}}/></div></div><div><div className="flex justify-between font-mono text-[7px] text-white/30"><span>INTENSITY DYNAMIC</span><span>{(dataset.stats.max-dataset.stats.min).toFixed(1)}</span></div><div className="mt-1 h-1 rounded bg-white/10"><div className="h-full w-[78%] rounded bg-violet-300"/></div></div></div></section><section className="rounded-xl border border-white/10 p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/25">ROI ANALYSIS</div>{["Whole brain","Cortex","Hippocampus","Motor cortex","Thalamus","Corpus callosum"].map(r=><button key={r} onClick={()=>{setRoi(r);setAnalysis(`ROI / ${r.toUpperCase()}`)}} className={`mt-2 flex w-full justify-between rounded-lg px-3 py-2 font-mono text-[7px] ${roi===r?"bg-cyan-200/[.07] text-cyan-100":"text-white/35 hover:bg-white/[.03]"}`}><span>{r}</span><span>{roi===r?"ACTIVE":"›"}</span></button>)}</section><section className="rounded-xl border border-white/10 p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/25">SLICE / HEATMAP</div><button onClick={()=>setHeat(v=>!v)} className="mt-3 w-full rounded-lg border border-white/10 py-2 font-mono text-[7px] text-white/45">{heat?"HEATMAP ON":"HEATMAP OFF"}</button><div className="mt-3 h-2 rounded-full bg-gradient-to-r from-blue-600 via-cyan-300 via-yellow-300 to-red-500"/><div className="mt-2 flex justify-between font-mono text-[6px] text-white/25"><span>LOW</span><span>INTENSITY</span><span>HIGH</span></div></section><section className="rounded-xl border border-white/10 p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/25">SESSION</div><button onClick={()=>setAnalysis("REPROCESSING…")} className="mt-3 w-full rounded-lg bg-white/[.04] py-2 font-mono text-[7px] text-white/55 hover:bg-white/[.08]">RE-RUN ANALYSIS</button><button onClick={()=>{setDataset(demoDataset());setFileName("NIMBLE_REFERENCE_T1");setAnalysis("RESET COMPLETE")}} className="mt-2 w-full rounded-lg border border-white/10 py-2 font-mono text-[7px] text-white/35">RESET DATASET</button></section></aside>
    </main>
    <div className="mx-auto max-w-[1900px] px-3 pb-4"><div className="rounded-xl border border-white/10 bg-white/[.012] p-3 font-mono text-[7px] leading-5 text-white/25">DATA PROVENANCE · Uploaded voxel statistics and volume-derived metrics are computed locally in this browser. Heatmaps, tract fields and NIMBLE navigation are visualization/research layers and are not clinical diagnoses.</div></div>
  </div>;
}
