import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { Brain, LogOut, Upload, Activity, Network, ScanLine, Waves } from "lucide-react";
import { VolumeBrain, type VolumeData } from "./VolumeBrain";

type Mode = "VOLUME" | "HEATMAP" | "TRACTS" | "EEG" | "CONNECTOME";
type Stats = { voxels:number; min:number; max:number; mean:number; std:number; dims:[number,number,number]; datatype:string; bitpix:number };
type Dataset = { volume: VolumeData; stats: Stats };

const demoDataset = (): Dataset => {
  const n=112, data=new Uint8Array(n*n*n), c=(n-1)/2; let sum=0,sum2=0,count=0,min=255,max=0;
  for(let z=0;z<n;z++)for(let y=0;y<n;y++)for(let x=0;x<n;x++){
    const X=(x-c)/c,Y=(y-c)/c,Z=(z-c)/c; const r=X*X/.9+Y*Y/.78+Z*Z/.84;
    const cortex=.06*Math.sin(Y*42+Z*9)+.025*Math.sin(Y*81-Z*11); let val=r<1+cortex?38+180*Math.pow(Math.max(0,1-r),.58):0;
    val+=32*Math.exp(-(X*X/.22+Y*Y/.28+Z*Z/.31)); val=Math.max(0,Math.min(255,val)); const i=x+n*(y+n*z); data[i]=val; sum+=val; sum2+=val*val; count++; min=Math.min(min,val); max=Math.max(max,val);
  }
  return {volume:{data,size:[n,n,n]},stats:{voxels:count,min,max,mean:sum/count,std:Math.sqrt(Math.max(0,sum2/count-(sum/count)**2)),dims:[n,n,n],datatype:"demo T1",bitpix:8}};
};

function parseNifti(buffer:ArrayBuffer): Dataset|null {
  const v=new DataView(buffer); if(v.byteLength<352)return null; const little=v.getInt32(0,true)===348; if(!little&&v.getInt32(0,false)!==348)return null;
  const i16=(o:number)=>v.getInt16(o,little), i32=(o:number)=>v.getInt32(o,little), f32=(o:number)=>v.getFloat32(o,little);
  const nx=i16(42),ny=i16(44),nz=i16(46),dt=i16(70),bp=i16(72); if(nx<2||ny<2||nz<2)return null;
  const slope=f32(112)||1, intercept=f32(116)||0, off=Math.max(352,f32(108)||352), bytes=bp/8, total=nx*ny*nz; if(bp%8||off+total*bytes>v.byteLength)return null;
  const raw=(i:number)=>{const o=off+i*bytes; switch(dt){case 2:return v.getUint8(o);case 4:return v.getInt16(o,little);case 8:return v.getInt32(o,little);case 16:return v.getFloat32(o,little);case 64:return v.getFloat64(o,little);case 256:return v.getInt8(o);case 512:return v.getUint16(o,little);case 768:return v.getUint32(o,little);default:return 0;}};
  const read=(i:number)=>raw(i)*slope+intercept; let min=Infinity,max=-Infinity,sum=0,sum2=0,samp=0; const step=Math.max(1,Math.ceil(Math.cbrt(total/250000)));
  for(let z=0;z<nz;z+=step)for(let y=0;y<ny;y+=step)for(let x=0;x<nx;x+=step){const q=read(x+nx*(y+ny*z));if(Number.isFinite(q)){min=Math.min(min,q);max=Math.max(max,q);sum+=q;sum2+=q*q;samp++;}}
  if(!samp)return null; const n=128,out=new Uint8Array(n*n*n),range=max-min||1;
  const sample=(x:number,y:number,z:number)=>read(x+nx*(y+ny*z));
  for(let z=0;z<n;z++)for(let y=0;y<n;y++)for(let x=0;x<n;x++){
    const fx=x*(nx-1)/(n-1),fy=y*(ny-1)/(n-1),fz=z*(nz-1)/(n-1),x0=Math.floor(fx),y0=Math.floor(fy),z0=Math.floor(fz),x1=Math.min(nx-1,x0+1),y1=Math.min(ny-1,y0+1),z1=Math.min(nz-1,z0+1),xd=fx-x0,yd=fy-y0,zd=fz-z0;
    const c000=sample(x0,y0,z0),c100=sample(x1,y0,z0),c010=sample(x0,y1,z0),c110=sample(x1,y1,z0),c001=sample(x0,y0,z1),c101=sample(x1,y0,z1),c011=sample(x0,y1,z1),c111=sample(x1,y1,z1);
    const c00=c000+(c100-c000)*xd,c10=c010+(c110-c010)*xd,c01=c001+(c101-c001)*xd,c11=c011+(c111-c011)*xd,c0=c00+(c10-c00)*yd,c1=c01+(c11-c01)*yd,q=Math.max(0,Math.min(1,(c0+(c1-c0)*zd-min)/range)); out[x+n*(y+n*z)]=Math.round(q*255);
  }
  return {volume:{data:out,size:[n,n,n]},stats:{voxels:total,min,max,mean:sum/samp,std:Math.sqrt(Math.max(0,sum2/samp-(sum/samp)**2)),dims:[nx,ny,nz],datatype:`NIfTI ${dt}`,bitpix:bp}};
}

function Heatmap({volume}:{volume:VolumeData}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const [nx,ny,nz]=volume.size,W=420,H=420;c.width=W;c.height=H;const img=ctx.createImageData(W,H),d=volume.data;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const vx=Math.floor(x*(nx-1)/(W-1)),vy=Math.floor(y*(ny-1)/(H-1)),vz=Math.floor(nz*.52),q=(d[vx+nx*(vy+ny*vz)]||0)/255,p=(y*W+x)*4;const h=(1-q)*240;const k=h/60, r=Math.max(0,Math.min(255,255*Math.abs((k%2)-1))),g=Math.max(0,Math.min(255,255*(1-Math.abs((k%2)-1))));img.data[p]=q*255;img.data[p+1]=g;img.data[p+2]=r;img.data[p+3]=q>.03?230:0;}ctx.putImageData(img,0,0)},[volume]);return <canvas ref={ref} className="h-full w-full rounded-xl"/>}

function Tracts(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d")!;let raf=0,t=0;const draw=()=>{t+=.006;const w=c.clientWidth,h=c.clientHeight,d=Math.min(devicePixelRatio||1,2);if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0)}ctx.clearRect(0,0,w,h);for(let k=0;k<560;k++){const b=k%9,pts=80;ctx.beginPath();for(let i=0;i<pts;i++){const u=i/(pts-1),base=(k%70-35)/38;let x=(u-.5)*2.4,y=base*.8,z=Math.sin(k*.61)*.38;if(b===0){y*=.25;z+=Math.sin(u*Math.PI)*.48}else if(b===1){y+=Math.sin(u*Math.PI)*.6;z+=Math.cos(u*Math.PI)*.2}else if(b===2){z+=Math.sin(u*Math.PI)*.8;y+=Math.sin(u*2*Math.PI)*.2}else if(b===3){y-=Math.sin(u*Math.PI)*.7;z+=Math.sin(u*Math.PI)*.35}else if(b===4){y+=Math.sin(u*2*Math.PI)*.35;z-=Math.sin(u*Math.PI)*.5}else if(b===5){x+=Math.sin(u*Math.PI)*.25;y+=Math.sin(u*3*Math.PI)*.22}else if(b===6){y+=Math.cos(u*Math.PI)*.35;z+=Math.sin(u*2*Math.PI)*.3}else if(b===7){y+=Math.sin(u*Math.PI)*.75;z+=Math.sin(u*Math.PI)*.18}else{z+=Math.cos(u*Math.PI)*.45;y+=Math.sin(u*2*Math.PI)*.25}const X=x*Math.cos(t)-z*Math.sin(t),Z=x*Math.sin(t)+z*Math.cos(t),p=3.4/(3.8-Z),sx=w/2+X*w*.31*p,sy=h/2+y*h*.27*p;i?ctx.lineTo(sx,sy):ctx.moveTo(sx,sy)}const hue=b%3===0?190:b%3===1?220:285;ctx.strokeStyle=`hsla(${hue},100%,${b<3?78:65}%,${b<3?.9:.55})`;ctx.lineWidth=b<3?1.7:1;ctx.shadowBlur=b<3?10:3;ctx.shadowColor=`hsla(${hue},100%,70%,.8)`;ctx.stroke()}ctx.shadowBlur=0;raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[]);return <canvas ref={ref} className="h-full w-full"/>}

function EEG(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d")!;let raf=0,t=0;const draw=()=>{t+=.018;const w=c.clientWidth,h=c.clientHeight,d=Math.min(devicePixelRatio||1,2);if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0)}ctx.clearRect(0,0,w,h);for(let ch=0;ch<8;ch++){ctx.beginPath();for(let x=0;x<w;x+=2){const y=18+ch*(h-36)/8+Math.sin(x*.025+t*(1+ch*.04))*8+Math.sin(x*.13+t*1.7)*2.5;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=`rgba(70,255,188,${.75-ch*.04})`;ctx.stroke()}raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[]);return <canvas ref={ref} className="h-full w-full"/>}

export function NimbleRealTimeAnalysisFixed(){
  const navigate=useNavigate(); const [dataset,setDataset]=useState<Dataset>(()=>demoDataset()); const [mode,setMode]=useState<Mode>("VOLUME"); const [roi,setRoi]=useState("Whole brain"); const [status,setStatus]=useState("READY"); const [fileName,setFileName]=useState("NIMBLE_REFERENCE_T1"); const fileRef=useRef<HTMLInputElement>(null);
  const quality=useMemo(()=>Math.min(99,82+(dataset.stats.std/Math.max(1,dataset.stats.max))*12),[dataset]);
  const upload=(f:File)=>{setStatus("PARSING VOXELS…");f.arrayBuffer().then(b=>{const p=parseNifti(b);if(p){setDataset(p);setFileName(f.name);setStatus("VOLUME READY")}else setStatus("NIfTI PARSE ERROR")}).catch(()=>setStatus("READ ERROR"))};
  const logout=()=>{localStorage.removeItem("cognivance_session");navigate({to:"/auth"})};
  return <div className="min-h-screen bg-[#020405] text-white"><input ref={fileRef} type="file" accept=".nii,.nii.gz" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><header className="border-b border-white/10 px-4 py-3"><div className="mx-auto flex max-w-[1900px] items-center justify-between"><div className="flex items-center gap-3"><Brain className="text-cyan-200" size={18}/><div><div className="font-mono text-[9px] tracking-[.3em] text-cyan-100">NIMBLE / RESEARCH OS</div><div className="font-mono text-[6px] tracking-[.2em] text-white/30">MULTIMODAL NEUROIMAGING • {status}</div></div></div><div className="flex gap-2"><button onClick={()=>navigate({to:"/"})} className="rounded-full border border-white/10 px-4 py-2 font-mono text-[7px] tracking-[.18em]">← HOME</button><button onClick={logout} className="flex items-center gap-2 rounded-full border border-red-200/15 px-4 py-2 font-mono text-[7px] tracking-[.18em] text-red-200/70"><LogOut size={11}/> LOGOUT</button></div></div></header>
    <main className="mx-auto grid max-w-[1900px] gap-3 p-3 lg:grid-cols-[250px_minmax(0,1fr)_310px]">
      <aside className="space-y-3"><section className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/30">DATA INGEST</div><button onClick={()=>fileRef.current?.click()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-cyan-200/20 bg-cyan-200/[.05] py-3 font-mono text-[7px] tracking-[.15em] text-cyan-100"><Upload size={12}/> UPLOAD .NII</button><div className="mt-3 truncate font-mono text-[7px] text-white/35">{fileName}</div></section><section className="rounded-2xl border border-white/10 bg-white/[.02] p-3"><div className="font-mono text-[7px] tracking-[.25em] text-white/30">VISUAL LAYERS</div>{(["VOLUME","HEATMAP","TRACTS","EEG","CONNECTOME"] as Mode[]).map(m=><button key={m} onClick={()=>setMode(m)} className={`mt-2 w-full rounded-lg px-3 py-2 text-left font-mono text-[7px] tracking-[.16em] ${mode===m?"bg-cyan-200/10 text-cyan-100":"text-white/45 hover:bg-white/5"}`}>{m}</button>)}</section><section className="rounded-2xl border border-white/10 bg-white/[.02] p-3"><div className="font-mono text-[7px] tracking-[.25em] text-white/30">ROI</div>{["Whole brain","Hippocampus","Motor cortex","Thalamus","Corpus callosum"].map(r=><button key={r} onClick={()=>setRoi(r)} className={`mt-2 w-full rounded-lg px-3 py-2 text-left font-mono text-[7px] ${roi===r?"text-cyan-100 bg-cyan-200/10":"text-white/40"}`}>{r}</button>)}</section></aside>
      <section className="min-h-[680px] rounded-2xl border border-white/10 bg-[#030708] p-3"><div className="flex items-center justify-between px-2 py-2"><div><div className="font-mono text-[7px] tracking-[.25em] text-white/30">LIVE VISUALIZATION</div><div className="mt-1 text-sm text-white/75">{mode} · {roi}</div></div><div className="font-mono text-[7px] text-emerald-300/60">● LIVE</div></div><div className="mt-2 h-[590px] overflow-hidden rounded-xl border border-white/10 bg-black">{mode==="VOLUME"&&<VolumeBrain volume={dataset.volume}/>} {mode==="HEATMAP"&&<Heatmap volume={dataset.volume}/>} {mode==="TRACTS"&&<Tracts/>} {mode==="EEG"&&<EEG/>} {mode==="CONNECTOME"&&<Tracts/>}</div></section>
      <aside className="space-y-3"><section className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/30">REAL-TIME ANALYSIS</div><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="VOXELS" value={dataset.stats.voxels.toLocaleString()}/><Metric label="MEAN" value={dataset.stats.mean.toFixed(2)}/><Metric label="STD" value={dataset.stats.std.toFixed(2)}/><Metric label="QC" value={`${quality.toFixed(0)}%`}/></div></section><section className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/30">VOLUME METADATA</div><div className="mt-3 space-y-2 font-mono text-[7px] text-white/45"><div className="flex justify-between"><span>DIMS</span><span>{dataset.stats.dims.join(" × ")}</span></div><div className="flex justify-between"><span>DATATYPE</span><span>{dataset.stats.datatype}</span></div><div className="flex justify-between"><span>BITPIX</span><span>{dataset.stats.bitpix}</span></div><div className="flex justify-between"><span>RANGE</span><span>{dataset.stats.min.toFixed(1)} — {dataset.stats.max.toFixed(1)}</span></div></div></section><section className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><div className="font-mono text-[7px] tracking-[.25em] text-white/30">ANALYSIS STATUS</div><div className="mt-3 flex items-center gap-2 text-emerald-300/70"><Activity size={13}/> <span className="font-mono text-[8px]">{status}</span></div><button onClick={()=>setStatus("ANALYSIS COMPLETE")} className="mt-4 w-full rounded-xl border border-cyan-200/15 py-3 font-mono text-[7px] tracking-[.16em] text-cyan-100">RUN ANALYSIS</button></section></aside>
    </main></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-white/[.02] p-3"><div className="font-mono text-[6px] tracking-[.2em] text-white/30">{label}</div><div className="mt-1 text-lg font-light text-white/85">{value}</div></div>}
