import { useEffect, useMemo, useRef, useState } from "react";

type Mode = "ANATOMY" | "CIRCUIT" | "SIGNAL" | "NAV";
const MRI = "https://upload.wikimedia.org/wikipedia/commons/b/b2/MRI_of_Human_Brain.jpg";
const modes = [
  { id: "ANATOMY" as Mode, label: "Anatomy", description: "MRI-derived anatomical structure" },
  { id: "CIRCUIT" as Mode, label: "Circuit reconstruction", description: "Simulated pathway reconstruction layer" },
  { id: "SIGNAL" as Mode, label: "Signal propagation", description: "Simulated propagation layer" },
  { id: "NAV" as Mode, label: "Nanorobot navigation", description: "Simulated NIMBLE navigation concept" },
];
const nodes = [[31,36],[39,28],[48,34],[57,25],[68,35],[73,47],[62,55],[52,48],[43,59],[33,52],[55,67],[67,62]] as const;

function ResearchCanvas({ mode }: { mode: Mode }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current; if (!canvas) return;
    const ctx = canvas.getContext("2d"); if (!ctx) return;
    let raf = 0, t = 0, width = 0, height = 0;
    const particles = Array.from({ length: mode === "NAV" ? 110 : 80 }, () => ({ x: Math.random(), y: Math.random(), z: Math.random(), phase: Math.random()*6.28, speed: .15+Math.random()*.55, size: .5+Math.random()*1.8 }));
    const resize = () => { const dpr=Math.min(window.devicePixelRatio||1,2); width=canvas.clientWidth; height=canvas.clientHeight; canvas.width=width*dpr; canvas.height=height*dpr; ctx.setTransform(dpr,0,0,dpr,0,0); };
    resize(); window.addEventListener("resize",resize);
    const draw=()=>{ t+=.012; ctx.clearRect(0,0,width,height); const hue=mode==="NAV"?"255,155,62":mode==="CIRCUIT"?"174,112,255":mode==="SIGNAL"?"70,245,180":"80,220,255";
      ctx.save(); ctx.translate(width*.5,height*.51); for(let r=90;r<Math.min(width,height)*.48;r+=34){ctx.beginPath();ctx.ellipse(0,0,r,r*.32,Math.sin(t*.35)*.15,0,Math.PI*2);ctx.strokeStyle=`rgba(${hue},${r<170?.20:.07})`;ctx.stroke();} ctx.restore();
      for(const p of particles){const x=width*(.15+p.x*.7)+Math.sin(t*p.speed+p.phase)*10*p.z,y=height*(.12+p.y*.76)+Math.cos(t*p.speed+p.phase)*8*p.z;ctx.beginPath();ctx.arc(x,y,p.size*(.45+p.z),0,6.28);ctx.fillStyle=`rgba(${hue},${.07+p.z*.35})`;ctx.fill();}
      if(mode==="SIGNAL"){const sx=width*.32+Math.sin(t)*20,sy=height*.47,gx=width*.7,gy=height*.43,grad=ctx.createLinearGradient(sx,sy,gx,gy);grad.addColorStop(0,`rgba(${hue},0)`);grad.addColorStop(.5,`rgba(${hue},.85)`);grad.addColorStop(1,`rgba(${hue},0)`);ctx.strokeStyle=grad;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(sx,sy);ctx.bezierCurveTo(width*.45,height*.28,width*.56,height*.64,gx,gy);ctx.stroke();}
      raf=requestAnimationFrame(draw);}; draw(); return()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",resize);};
  },[mode]);
  return <canvas ref={ref} className="pointer-events-none absolute inset-0 h-full w-full" aria-hidden="true"/>;
}

function BrainHologram({ mode, tilt }: { mode: Mode; tilt: {x:number;y:number} }) {
  const active=mode!=="ANATOMY"; const color=mode==="NAV"?"#ffad52":mode==="CIRCUIT"?"#b58cff":mode==="SIGNAL"?"#4df5b8":"#63eaff";
  return <div className="absolute left-1/2 top-1/2 h-[78%] w-[82%] -translate-x-1/2 -translate-y-1/2" style={{transform:`translate(-50%,-50%) perspective(1100px) rotateX(${tilt.y}deg) rotateY(${tilt.x}deg)`,transformStyle:"preserve-3d"}}>
    <div className="absolute inset-[8%] rounded-[50%] bg-cyan-300/[.06] blur-[75px]"/>
    {[0,1,2,3].map(i=><img key={i} src={MRI} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-contain grayscale contrast-[1.55] brightness-[1.18] mix-blend-screen" style={{transform:`translateZ(${i*10}px) translate(${i*1.5}px,${-i*.8}px)`,opacity:.13+i*.035}}/>)}
    <img src={MRI} alt="T1-weighted MRI-derived brain visualization" className="absolute inset-0 h-full w-full object-contain grayscale contrast-[1.7] brightness-[1.2] mix-blend-screen" style={{opacity:.82}}/>
    <svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none"><defs><filter id="nGlow"><feGaussianBlur stdDeviation=".8" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="brainPath"><stop stopColor={color} stopOpacity=".04"/><stop offset=".5" stopColor={color} stopOpacity=".9"/><stop offset="1" stopColor={color} stopOpacity=".04"/></linearGradient></defs>{Array.from({length:18},(_,i)=>{const y=24+i*2.9;return <path key={i} d={`M20 ${y} C31 ${y-17},37 ${y+17},48 ${y} S66 ${y-16},80 ${y+3}`} fill="none" stroke="url(#brainPath)" strokeWidth={active?.42:.18} strokeDasharray={mode==="SIGNAL"?"1.2 2.5":undefined} className={mode==="SIGNAL"?"nimble-flow":""}/>})}<path d="M36 46 C43 32 53 36 57 45 C61 55 55 61 48 54 C42 48 39 59 31 61" fill="none" stroke={color} strokeOpacity={active?.7:.18} strokeWidth=".8" filter="url(#nGlow)"/>{nodes.map(([cx,cy],i)=><g key={i} className={active?"nimble-pulse":""} style={{animationDelay:`${i*120}ms`}}><circle cx={cx} cy={cy} r={mode==="NAV"?1.1:.75} fill={color} opacity={active?.9:.25} filter="url(#nGlow)"/><circle cx={cx} cy={cy} r="2.5" fill="none" stroke={color} strokeOpacity={active?.28:.08}/></g>)}</svg>
    {mode==="NAV"&&<div className="absolute left-[48%] top-[44%] h-3 w-3 rounded-full bg-orange-300 shadow-[0_0_22px_8px_rgba(255,150,60,.28)] animate-pulse"/>}
  </div>;
}

export function NimbleMRIShowcase() {
  const [mode,setMode]=useState<Mode>("ANATOMY"); const [tilt,setTilt]=useState({x:0,y:0}); const [slice,setSlice]=useState(128); const active=useMemo(()=>modes.find(m=>m.id===mode)!,[mode]);
  return <section className="relative overflow-hidden bg-[#020406] text-white"><style>{`@keyframes flow{to{stroke-dashoffset:-28}}@keyframes pulse{50%{transform:scale(1.65);opacity:.35}}@keyframes scan{0%{transform:translateY(-100%)}100%{transform:translateY(1000%)}}.nimble-flow{animation:flow 1.8s linear infinite}.nimble-pulse{transform-box:fill-box;transform-origin:center;animation:pulse 1.8s ease-in-out infinite}`}</style><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_38%,rgba(35,160,220,.09),transparent_38%),radial-gradient(circle_at_20%_80%,rgba(130,75,255,.06),transparent_32%)]"/>
    <div className="relative mx-auto max-w-[1600px] px-4 py-8 sm:px-7 lg:px-10 lg:py-14"><div className="mb-6 flex flex-wrap items-end justify-between gap-6 border-b border-white/10 pb-6"><div><div className="mb-3 font-mono text-[8px] uppercase tracking-[.38em] text-cyan-300/70">COGNIVANCE LABS / INSTRUMENT PROGRAMME</div><h1 className="max-w-5xl text-3xl font-medium tracking-[-.055em] sm:text-5xl lg:text-[58px] lg:leading-[.98]">NIMBLE <span className="text-white/25">—</span> neural intelligence mapping &amp; bioelectronic lab environment.</h1></div><div className="min-w-[250px] text-right font-mono text-[8px] uppercase tracking-[.18em] text-white/35"><div className="text-cyan-300/70">LIVE RESEARCH CONSOLE</div><div className="mt-2">MRI-DERIVED / SIMULATION LAYERS / ONLINE</div></div></div>
      <div className="grid gap-3 xl:grid-cols-[240px_minmax(0,1fr)_310px]">
        <aside className="order-2 rounded-2xl border border-white/10 bg-white/[.025] p-4 xl:order-1"><div className="font-mono text-[8px] uppercase tracking-[.3em] text-white/30">MRI volume</div><div className="mt-4 flex items-center justify-between border-b border-white/10 pb-3"><span className="text-[11px] text-white/65">sub-01_T1w</span><span className="text-[8px] text-emerald-300">● ONLINE</span></div><div className="mt-4 space-y-4 font-mono text-[8px] text-white/35"><div><span className="block text-white/20">MODALITY</span><b className="font-normal text-white/60">T1-weighted</b></div><div><span className="block text-white/20">RESOLUTION</span><b className="font-normal text-white/60">1.0 × 1.0 × 1.0 mm</b></div><div><span className="block text-white/20">DIMENSIONS</span><b className="font-normal text-white/60">256 × 256 × 256</b></div><div><span className="block text-white/20">ORIENTATION</span><b className="font-normal text-white/60">RAS</b></div></div><div className="mt-6 border-t border-white/10 pt-5 font-mono text-[8px] uppercase tracking-[.25em] text-white/30">View controls</div><div className="mt-4 space-y-3 text-[9px] text-white/45"><div>◌ ROTATE <span className="float-right text-white/20">POINTER</span></div><div>⌕ ZOOM <span className="float-right text-white/20">WHEEL</span></div><div>✥ PAN <span className="float-right text-white/20">DRAG</span></div></div><div className="mt-6 border-t border-white/10 pt-5 font-mono text-[8px] uppercase tracking-[.25em] text-white/30">Slice</div><input aria-label="MRI slice" type="range" min="1" max="256" value={slice} onChange={e=>setSlice(Number(e.target.value))} className="mt-4 w-full accent-cyan-300"/><div className="mt-2 flex justify-between font-mono text-[8px] text-white/25"><span>001</span><span>z = {slice}</span><span>256</span></div></aside>
        <main className="relative order-1 min-h-[650px] overflow-hidden rounded-2xl border border-white/10 bg-[#010304] xl:order-2" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setTilt({x:((e.clientX-r.left)/r.width-.5)*10,y:-((e.clientY-r.top)/r.height-.5)*7})}} onMouseLeave={()=>setTilt({x:0,y:0})}><div className="absolute inset-0 opacity-[.25]" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px)",backgroundSize:"28px 28px"}}/><ResearchCanvas mode={mode}/><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,transparent_34%,rgba(0,3,5,.76)_92%)]"/><div className="absolute left-5 top-5 z-20 font-mono text-[8px] uppercase tracking-[.25em] text-white/35">● MRI VOLUME / ONLINE</div><div className="absolute right-5 top-5 z-20 rounded-full border border-cyan-200/15 bg-black/60 px-3 py-1 font-mono text-[8px] uppercase tracking-[.2em] text-cyan-200/70">{active.label}</div><BrainHologram mode={mode} tilt={tilt}/><div className="absolute bottom-5 left-5 right-5 z-20 flex justify-between font-mono text-[7px] uppercase tracking-[.18em] text-white/25"><span>T1W / 256³ / RAS</span><span>{mode==="ANATOMY"?"ANATOMICAL REFERENCE":"SIMULATION LAYER ACTIVE"}</span></div><div className="absolute left-0 right-0 top-0 h-px bg-cyan-200/40 shadow-[0_0_15px_rgba(100,230,255,.6)] animate-[scan_5s_linear_infinite] opacity-30"/></main>
        <aside className="order-3 rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="font-mono text-[8px] uppercase tracking-[.3em] text-white/30">Research modes</div><div className="mt-3 space-y-2">{modes.map((item,i)=><button key={item.id} onClick={()=>setMode(item.id)} className={`w-full rounded-lg border p-4 text-left transition-all duration-300 ${mode===item.id?"border-cyan-200/40 bg-cyan-200/[.055] shadow-[0_0_28px_rgba(70,210,255,.06)]":"border-white/10 bg-black/10 hover:border-white/20"}`}><div className="flex items-center justify-between"><span className="font-mono text-[8px] text-white/25">0{i+1}</span><span className={`h-1.5 w-1.5 rounded-full ${mode===item.id?"bg-cyan-200 shadow-[0_0_12px_#7df3ff]":"bg-white/15"}`}/></div><div className="mt-3 text-[12px] font-medium">{item.label}</div><div className="mt-1 text-[9px] leading-4 text-white/35">{item.description}</div></button>)}</div><div className="mt-5 border-t border-white/10 pt-5 font-mono text-[8px] uppercase tracking-[.25em] text-white/30">Live system feed</div><div className="mt-3 space-y-3 text-[9px] text-white/50"><div className="flex justify-between"><span>DATA STREAM</span><span className="text-emerald-300">STABLE ●</span></div><div className="flex justify-between"><span>RENDER FPS</span><span>60 FPS</span></div><div className="flex justify-between"><span>LATENCY</span><span>12 ms</span></div><div className="flex justify-between"><span>MODEL STATE</span><span className="text-cyan-200">ONLINE</span></div></div><div className="mt-6 border-t border-white/10 pt-5 font-mono text-[8px] uppercase tracking-[.25em] text-white/30">Signal activity</div><div className="mt-3 h-16 overflow-hidden rounded border border-white/10 bg-black/30"><svg viewBox="0 0 300 70" className="h-full w-full"><polyline points="0,56 12,52 22,54 32,38 42,46 52,24 62,45 72,40 82,50 94,18 105,35 115,32 126,47 137,28 149,43 161,20 172,38 184,31 196,44 207,22 218,36 230,26 242,41 255,30 267,35 280,18 300,26" fill="none" stroke="#63eaff" strokeWidth="1.4" opacity=".75"/></svg></div></aside>
      </div>
      <div className="mt-3 grid gap-3 lg:grid-cols-[1.1fr_1fr_1fr]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="font-mono text-[8px] uppercase tracking-[.28em] text-white/30">MRI slices</div><div className="mt-3 grid grid-cols-3 gap-2">{["AXIAL","CORONAL","SAGITTAL"].map((name,i)=><button key={name} onClick={()=>setSlice(80+i*48)} className="overflow-hidden rounded border border-white/10 bg-black/30 text-left hover:border-cyan-200/30"><img src={MRI} alt="MRI slice reference" className="h-20 w-full object-cover grayscale contrast-[1.5] brightness-[1.2]"/><div className="p-2 font-mono text-[7px] text-white/35">{name}<br/>{i===0?"z":i===1?"y":"x"} = {80+i*48}</div></button>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="font-mono text-[8px] uppercase tracking-[.28em] text-white/30">Tissue intensity distribution</div><div className="mt-4 h-24"><svg viewBox="0 0 420 100" className="h-full w-full"><path d="M0 90 C25 80 30 20 60 50 S95 90 120 65 S150 15 180 50 S220 95 250 62 S285 10 315 42 S350 86 375 55 S400 25 420 30" fill="none" stroke="#63eaff" strokeWidth="1.5"/></svg></div><div className="flex justify-between font-mono text-[7px] text-white/20"><span>0</span><span>1024</span><span>2048</span><span>3072</span><span>4095</span></div></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="font-mono text-[8px] uppercase tracking-[.28em] text-white/30">Volume composition</div><div className="mt-4 grid grid-cols-[1fr_80px] items-center gap-3"><div className="space-y-2 text-[9px] text-white/45"><div>● Gray matter <span className="float-right">41.2%</span></div><div>● White matter <span className="float-right">32.7%</span></div><div>● CSF <span className="float-right">18.6%</span></div></div><div className="h-20 w-20 rounded-full border-[12px] border-cyan-300/50 border-r-violet-300/60 border-b-fuchsia-300/50"/></div></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-5 font-mono text-[8px] uppercase tracking-[.22em] text-white/25"><span>COGNIVANCE LABS</span><span>ADVANCING NEURONANOTECHNOLOGY</span><span>NIMBLE / RESEARCH CONSOLE v1.0</span></div>
    </div>
  </section>;
}
